//
//  NewPostWorker.swift
//  ParentsJournal
//
//  Created by Ngoc LE on 4/25/19.
//  Copyright (c) 2019 LifeOfCoder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NewPostWorker
{
  func doSomeWork()
  {
  }
}
