//
//  NewPostInteractor.swift
//  ParentsJournal
//
//  Created by Ngoc LE on 4/25/19.
//  Copyright (c) 2019 LifeOfCoder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewPostBusinessLogic
{
  func doSomething(request: NewPost.Something.Request)
}

protocol NewPostDataStore
{
  //var name: String { get set }
}

class NewPostInteractor: NewPostBusinessLogic, NewPostDataStore
{
  var presenter: NewPostPresentationLogic?
  var worker: NewPostWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: NewPost.Something.Request)
  {
    worker = NewPostWorker()
    worker?.doSomeWork()
    
    let response = NewPost.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
