//
//  MainRouter.swift
//  ParentsJournal
//
//  Created by Ngoc Tuan Le on 4/14/19.
//  Copyright (c) 2019 LifeOfCoder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
  func navigateToNewPost(segue: UIStoryboardSegue?)
}

protocol MainDataPassing {
  var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
  weak var viewController: MainViewController?
  var dataStore: MainDataStore?
  
  // MARK: Routing
  
  func navigateToNewPost(segue: UIStoryboardSegue?) {
    if let segue = segue {
      guard let destinationVC = segue.destination as? NewPostViewController,
        var destinationDS = destinationVC.router?.dataStore else {
          return
      }
      
      passDataToNewPost(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      guard let destinationVC = storyboard.instantiateViewController(withIdentifier: "NewPostViewController") as? NewPostViewController,
        var destinationDS = destinationVC.router?.dataStore else {
          return
      }
      
      passDataToNewPost(source: dataStore!, destination: &destinationDS)
      navigateToNewPost(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToNewPost(source: MainViewController, destination: NewPostViewController) {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToNewPost(source: MainDataStore, destination: inout NewPostDataStore) {
    
  }
}
