//
//  LaunchPresenter.swift
//  ParentsJournal
//
//  Created by Ngoc LE on 4/18/19.
//  Copyright (c) 2019 LifeOfCoder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LaunchPresentationLogic {
  func presentSomething(response: Launch.Something.Response)
}

class LaunchPresenter: LaunchPresentationLogic {
  weak var viewController: LaunchDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Launch.Something.Response) {
    let viewModel = Launch.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
