//
//  LoginInteractor.swift
//  ParentsJournal
//
//  Created by Ngoc Tuan Le on 4/14/19.
//  Copyright (c) 2019 LifeOfCoder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
  func setupView()
  func login(request: Login.Something.Request)
}

protocol LoginDataStore {
  //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
  //var name: String = ""
  
  func setupView() {
    presenter?.setupView()
  }
  
  func login(request: Login.Something.Request) {
    worker = LoginWorker()
    worker?.login()
    
    let response = Login.Something.Response()
    presenter?.presentMainScreen(response: response)
  }
}
